name: model-env
channels:
  - conda-forge
dependencies:
  - lightning
  - pip:
      - inference-schema[numpy-support]==1.3.0
      - xlrd==2.0.1
      - mlflow== 2.4.1
      - azureml-mlflow==1.51.0
