name: Build and Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Version number for this release"
        required: true
        type: string

permissions:
  contents: write
  discussions: write

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            output_name: minecraft-schematic-generator.exe
            torch_index: cu124
          - os: ubuntu-latest
            output_name: minecraft-schematic-generator-linux
            torch_index: cu124
          - os: macos-latest
            output_name: minecraft-schematic-generator-mac
            torch_index: cpu

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install PyTorch with CUDA
        if: matrix.os != 'macos-latest'
        run: |
          python -m pip install --upgrade pip
          pip install torch --index-url https://download.pytorch.org/whl/${{ matrix.torch_index }}

      - name: Install PyTorch CPU (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          python -m pip install --upgrade pip
          pip install torch

      - name: Install PyInstaller and minimal dependencies
        run: |
          # Install only server dependencies
          pip install -e .[server]
          pip install pyinstaller

      - name: Install UPX (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install upx

      - name: Install UPX (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install upx

      - name: Install UPX (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          $url = "https://github.com/upx/upx/releases/download/v4.2.1/upx-4.2.1-win64.zip"
          Invoke-WebRequest -Uri $url -OutFile upx.zip
          Expand-Archive upx.zip -DestinationPath upx
          echo "$pwd\upx\upx-4.2.1-win64" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Build binary
        run: |
          pyinstaller --onefile \
            --name ${{ matrix.output_name }} \
            --upx-dir="${{ matrix.os == 'windows-latest' && 'upx\upx-4.2.1-win64' || '/usr/bin' }}" \
            --strip \
            --noupx-exclude \
            --exclude-module PIL \
            --exclude-module numpy \
            --exclude-module pandas \
            --copy-metadata safetensors \
            --collect-data minecraft_schematic_generator \
            app/main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.output_name }}
          path: dist/${{ matrix.output_name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: dist

      - name: Install 7-Zip
        run: sudo apt-get install p7zip-full

      - name: Compress binaries
        run: |
          cd dist
          7z a minecraft-schematic-generator.exe.7z minecraft-schematic-generator.exe/minecraft-schematic-generator.exe
          7z a minecraft-schematic-generator-linux.7z minecraft-schematic-generator-linux/minecraft-schematic-generator-linux
          7z a minecraft-schematic-generator-mac.7z minecraft-schematic-generator-mac/minecraft-schematic-generator-mac

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ inputs.release_version }}
          name: Release v${{ inputs.release_version }}
          draft: false
          prerelease: false
          files: |
            dist/*.7z
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
