name: Build and Release


on:
  release:
    types: [created]
  push:

permissions:
  contents: write
  discussions: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            output_name: minecraft-schematic-generator.exe
            torch_index: cpu
            cuda: false
          - os: ubuntu-latest
            output_name: minecraft-schematic-generator-linux
            torch_index: cpu
            cuda: false
          - os: macos-latest
            output_name: minecraft-schematic-generator-mac
            torch_index: cpu
            cuda: false
          - os: windows-latest
            output_name: minecraft-schematic-generator.exe
            torch_index: cu124
            cuda: true
          - os: ubuntu-latest
            output_name: minecraft-schematic-generator-linux
            torch_index: cu124
            cuda: true
          - os: ubuntu-latest
            output_name: minecraft-schematic-generator-termux
            torch_index: cpu
            cuda: false
            termux: true

    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Setup cross-compilation environment
        if:  ${{ matrix.termux }}
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
          sudo apt-get install -y crossbuild-essential-arm64
          sudo apt-get install -y python3-pip python3-dev
          sudo apt-get install -y patchelf

      - name: Install PyTorch
        shell: bash
        run: |
          python -m pip install --upgrade pip
          if [ "${{ matrix.termux }}" = "true" ]; then
            export PYTHONNOUSERSITE=1
            pip install torch==2.6.0+cpu --index-url https://download.pytorch.org/whl/cpu
          else
            pip install torch --index-url https://download.pytorch.org/whl/${{ matrix.torch_index }}
          fi

      - name: Install PyInstaller and dependencies
        run: |
          pip install -e .[server]
          pip install pyinstaller ${{ matrix.cuda && 'huggingface_hub' || '' }}

      - name: Generate version file
        shell: bash
        run: |
          VERSION=${{ github.ref_name }}
          # Remove 'v' prefix if present
          VERSION=${VERSION#v}
          echo "# This file is auto-generated during build" > src/minecraft_schematic_generator/version.py
          echo "__version__ = \"${VERSION}\"" >> src/minecraft_schematic_generator/version.py
          echo "GITHUB_REPO = \"mmmfrieddough/minecraft-schematic-generator\"" >> src/minecraft_schematic_generator/version.py
      - name: Setup cross-compilation environment
        if: ${{ matrix.termux }}
        run: |
          # 安装交叉编译工具链
          sudo apt-get update
          sudo apt-get install -y \
            gcc-aarch64-linux-gnu \
            g++-aarch64-linux-gnu \
            crossbuild-essential-arm64 \
            qemu-user-static \
            binutils-aarch64-linux-gnu \
            libc6-dev-arm64-cross

          # 添加ARM64架构支持
          sudo dpkg --add-architecture arm64
          sudo tee /etc/apt/sources.list.d/arm64.list >/dev/null <<EOF
          deb [arch=amd64] http://archive.ubuntu.com/ubuntu noble main restricted
          deb [arch=amd64] http://archive.ubuntu.com/ubuntu noble-updates main restricted
          deb [arch=amd64] http://security.ubuntu.com/ubuntu noble-security main restricted
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports noble main restricted universe multiverse
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports noble-updates main restricted universe multiverse
          deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports noble-security main restricted universe multiverse
          EOF

          # 更新包列表并安装ARM64运行时库
          sudo apt-get update -o APT::Architecture="amd64" -o APT::Architectures="amd64 arm64"
          sudo apt-get install -y \
            libpython3.12-dev:arm64 \
            zlib1g:arm64 \
            libssl3:arm64 \
            libffi8:arm64 \
            libopenblas-dev:arm64 \
            libatomic1:arm64

      - name: Install PyTorch for Termux
        if: ${{ matrix.termux }}
        run: |
          # 创建隔离的虚拟环境
          python -m venv .termux-venv
          source .termux-venv/bin/activate

          # 安装PyTorch（CPU版本）
          pip install --upgrade pip
          pip install torch==2.6.0 --index-url https://download.pytorch.org/whl/cpu

      - name: Install PyInstaller and project dependencies
        if: ${{ matrix.termux }}
        run: |
          source .termux-venv/bin/activate
          pip install pyinstaller==6.7.0
          pip install -e .[server]  # 安装项目依赖

      - name: Build binary termux
        shell: bash
        if: ${{ matrix.termux == true }}
        run: |
          # Cross-compilation configuration for Termux/Android ARM64
          export TERMUX_BUILD=1
          mkdir -p termux_build termux_dist

           # Configure cross-compilation environment variables
          export CC=aarch64-linux-gnu-gcc
          export CXX=aarch64-linux-gnu-g++
          export AR=aarch64-linux-gnu-ar
          export CFLAGS="-fPIC -I/usr/aarch64-linux-gnu/include"
          export CXXFLAGS="-fPIC -I/usr/aarch64-linux-gnu/include"
          export LDFLAGS="-pie -L/usr/aarch64-linux-gnu/lib -L/usr/lib/aarch64-linux-gnu"
          export TARGET_ARCH=aarch64
          export TARGET_OS=android
          export PYTHONPATH=$(pwd)

          # Prepare QEMU static interpreter
          sudo cp /usr/bin/qemu-aarch64-static .termux-venv/bin/
          export QEMU_LD_PREFIX=/usr/aarch64-linux-gnu

           # Build using PyInstaller
          pyinstaller --clean \
            --workpath termux_build \
            --distpath termux_dist \
            --name ${{ matrix.output_name }} \
            --onefile \
            --copy-metadata safetensors \
            --collect-data minecraft_schematic_generator \
            app/main.py

          # Verify the binary architecture
          echo "===== Binary Architecture ====="
          file termux_dist/${{ matrix.output_name }} || true
          echo -e "\n===== Dynamic Dependencies ====="
          patchelf --print-needed termux_dist/${{ matrix.output_name }} || true

          
          

      # ========== 其他构建步骤保持不变 ==========
      - name: Build binary normal
        shell: bash
        if: ${{ !matrix.termux }}
        run: |
            pyinstaller --onefile \
              --name ${{ matrix.output_name }} \
              --copy-metadata safetensors \
              --collect-data minecraft_schematic_generator \
              app/main.py

      - name: Upload artifact
        if: ${{ !matrix.cuda }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.output_name }}
          path: ${{ matrix.termux && 'termux_dist' || 'dist' }}/${{ matrix.output_name }}


  

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: |
            ## Download Options
            
            ### CUDA Version (Recommended)
            For optimal performance on Windows and Linux, download the CUDA-enabled version (hosted on Hugging Face due to file size limits):
            - [Windows CUDA](https://huggingface.co/mmmfrieddough/minecraft-schematic-generator/resolve/${{ github.ref_name }}/binaries/minecraft-schematic-generator.exe)
            - [Linux CUDA](https://huggingface.co/mmmfrieddough/minecraft-schematic-generator/resolve/${{ github.ref_name }}/binaries/minecraft-schematic-generator-linux)
            
            **Note:** CUDA version requires an NVIDIA GPU but provides significantly faster inference.
            
            ### CPU Version
            For macOS systems (best performance on Apple Silicon):
            - [macOS](dist/minecraft-schematic-generator-mac/minecraft-schematic-generator-mac)
            
            CPU versions for Windows/Linux are available but not recommended due to extremely slow inference times:
            - [Windows CPU](dist/minecraft-schematic-generator.exe/minecraft-schematic-generator.exe)
            - [Linux CPU](dist/minecraft-schematic-generator-linux/minecraft-schematic-generator-linux)
            
            ### Android/Termux Version
            - [Termux ARM64](dist/minecraft-schematic-generator-termux/minecraft-schematic-generator-termux)
            
            ## System Requirements
            - Windows/Linux: NVIDIA GPU strongly recommended
            - macOS: Apple Silicon recommended for best performance
            - Android: ARM64 device running Termux
            
            ## Server Configuration
            The server can be started with:
            ```bash
            ./minecraft-schematic-generator [options]
            ```
            
            By default, it will run on http://localhost:8000
          draft: false
          prerelease: false
          files: |
            dist/minecraft-schematic-generator*/minecraft-schematic-generator*
        env:
          GITHUB_TOKEN: ${{ secrets.GIT }}       
