name: Test Artifacts

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Create test files
        run: |
          mkdir -p dist
          echo "test" > dist/minecraft-schematic-generator.exe
          echo "test" > dist/minecraft-schematic-generator-linux
          echo "test" > dist/minecraft-schematic-generator-mac

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: minecraft-schematic-generator.exe
          path: dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: minecraft-schematic-generator-linux
          path: dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: minecraft-schematic-generator-mac
          path: dist

  download:
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: dist

      - name: List files
        run: ls -R dist
